-- Seed 001: Full 100-asset universe
-- Idempotent: ON CONFLICT (ticker) DO NOTHING
-- Sectors use standard GICS classifications for stocks, descriptive labels for ETFs/crypto.

INSERT INTO assets (ticker, name, asset_type, sector) VALUES

-- ============================================================
-- STOCKS (63)
-- ============================================================
('AAPL',  'Apple Inc.',                          'stock', 'Technology'),
('MSFT',  'Microsoft Corporation',               'stock', 'Technology'),
('NVDA',  'NVIDIA Corporation',                  'stock', 'Technology'),
('GOOGL', 'Alphabet Inc.',                       'stock', 'Communication Services'),
('AMZN',  'Amazon.com Inc.',                    'stock', 'Consumer Discretionary'),
('META',  'Meta Platforms Inc.',                 'stock', 'Communication Services'),
('TSLA',  'Tesla Inc.',                          'stock', 'Consumer Discretionary'),
('BRK.B', 'Berkshire Hathaway Inc. Class B',    'stock', 'Financials'),
('JPM',   'JPMorgan Chase & Co.',               'stock', 'Financials'),
('V',     'Visa Inc.',                           'stock', 'Financials'),
('JNJ',   'Johnson & Johnson',                  'stock', 'Healthcare'),
('UNH',   'UnitedHealth Group Incorporated',    'stock', 'Healthcare'),
('XOM',   'Exxon Mobil Corporation',            'stock', 'Energy'),
('PG',    'Procter & Gamble Co.',               'stock', 'Consumer Staples'),
('HD',    'The Home Depot Inc.',                'stock', 'Consumer Discretionary'),
('MA',    'Mastercard Incorporated',            'stock', 'Financials'),
('LLY',   'Eli Lilly and Company',              'stock', 'Healthcare'),
('ABBV',  'AbbVie Inc.',                        'stock', 'Healthcare'),
('MRK',   'Merck & Co. Inc.',                  'stock', 'Healthcare'),
('PEP',   'PepsiCo Inc.',                       'stock', 'Consumer Staples'),
('KO',    'The Coca-Cola Company',              'stock', 'Consumer Staples'),
('AVGO',  'Broadcom Inc.',                      'stock', 'Technology'),
('COST',  'Costco Wholesale Corporation',       'stock', 'Consumer Staples'),
('ADBE',  'Adobe Inc.',                         'stock', 'Technology'),
('CRM',   'Salesforce Inc.',                    'stock', 'Technology'),
('NFLX',  'Netflix Inc.',                       'stock', 'Communication Services'),
('AMD',   'Advanced Micro Devices Inc.',        'stock', 'Technology'),
('QCOM',  'QUALCOMM Incorporated',              'stock', 'Technology'),
('TXN',   'Texas Instruments Incorporated',     'stock', 'Technology'),
('HON',   'Honeywell International Inc.',       'stock', 'Industrials'),
('BA',    'The Boeing Company',                 'stock', 'Industrials'),
('CAT',   'Caterpillar Inc.',                   'stock', 'Industrials'),
('GS',    'The Goldman Sachs Group Inc.',       'stock', 'Financials'),
('MS',    'Morgan Stanley',                     'stock', 'Financials'),
('BAC',   'Bank of America Corporation',        'stock', 'Financials'),
('WMT',   'Walmart Inc.',                       'stock', 'Consumer Staples'),
('TGT',   'Target Corporation',                 'stock', 'Consumer Discretionary'),
('DIS',   'The Walt Disney Company',            'stock', 'Communication Services'),
('INTC',  'Intel Corporation',                  'stock', 'Technology'),
('IBM',   'International Business Machines',    'stock', 'Technology'),
('GE',    'GE Aerospace',                       'stock', 'Industrials'),
('F',     'Ford Motor Company',                 'stock', 'Consumer Discretionary'),
('GM',    'General Motors Company',             'stock', 'Consumer Discretionary'),
('UBER',  'Uber Technologies Inc.',             'stock', 'Industrials'),
('LYFT',  'Lyft Inc.',                          'stock', 'Industrials'),
('SHOP',  'Shopify Inc.',                       'stock', 'Technology'),
('SQ',    'Block Inc.',                         'stock', 'Financials'),
('PYPL',  'PayPal Holdings Inc.',               'stock', 'Financials'),
('NOW',   'ServiceNow Inc.',                    'stock', 'Technology'),
('SNOW',  'Snowflake Inc.',                     'stock', 'Technology'),
('PLTR',  'Palantir Technologies Inc.',         'stock', 'Technology'),
('COIN',  'Coinbase Global Inc.',               'stock', 'Financials'),
('RBLX',  'Roblox Corporation',                 'stock', 'Communication Services'),
('HOOD',  'Robinhood Markets Inc.',             'stock', 'Financials'),
('SOFI',  'SoFi Technologies Inc.',             'stock', 'Financials'),
('RIVN',  'Rivian Automotive Inc.',             'stock', 'Consumer Discretionary'),
('LCID',  'Lucid Group Inc.',                   'stock', 'Consumer Discretionary'),
('NIO',   'NIO Inc.',                           'stock', 'Consumer Discretionary'),
('BABA',  'Alibaba Group Holding Limited',      'stock', 'Consumer Discretionary'),
('JD',    'JD.com Inc.',                        'stock', 'Consumer Discretionary'),
('PDD',   'PDD Holdings Inc.',                  'stock', 'Consumer Discretionary'),
('PINS',  'Pinterest Inc.',                     'stock', 'Communication Services'),
('SNAP',  'Snap Inc.',                          'stock', 'Communication Services'),

-- ============================================================
-- ETFs (20)
-- ============================================================
('SPY',  'SPDR S&P 500 ETF Trust',             'etf', 'Broad Market'),
('QQQ',  'Invesco QQQ Trust',                  'etf', 'Technology'),
('IWM',  'iShares Russell 2000 ETF',           'etf', 'Small Cap'),
('VTI',  'Vanguard Total Stock Market ETF',    'etf', 'Broad Market'),
('VOO',  'Vanguard S&P 500 ETF',               'etf', 'Broad Market'),
('VEA',  'Vanguard FTSE Developed Markets ETF','etf', 'International Developed'),
('EEM',  'iShares MSCI Emerging Markets ETF',  'etf', 'Emerging Markets'),
('GLD',  'SPDR Gold Shares',                   'etf', 'Commodities'),
('SLV',  'iShares Silver Trust',               'etf', 'Commodities'),
('USO',  'United States Oil Fund LP',          'etf', 'Commodities'),
('TLT',  'iShares 20+ Year Treasury Bond ETF', 'etf', 'Fixed Income'),
('HYG',  'iShares iBoxx High Yield Corp Bond', 'etf', 'Fixed Income'),
('LQD',  'iShares iBoxx Investment Grade Corp','etf', 'Fixed Income'),
('XLK',  'Technology Select Sector SPDR Fund', 'etf', 'Technology'),
('XLF',  'Financial Select Sector SPDR Fund',  'etf', 'Financials'),
('XLE',  'Energy Select Sector SPDR Fund',     'etf', 'Energy'),
('XLV',  'Health Care Select Sector SPDR Fund','etf', 'Healthcare'),
('XLI',  'Industrial Select Sector SPDR Fund', 'etf', 'Industrials'),
('ARKK', 'ARK Innovation ETF',                 'etf', 'Innovation'),
('SCHD', 'Schwab US Dividend Equity ETF',      'etf', 'Dividend'),

-- ============================================================
-- CRYPTO (20)
-- ============================================================
('BTC',   'Bitcoin',             'crypto', 'Layer 1'),
('ETH',   'Ethereum',            'crypto', 'Layer 1'),
('BNB',   'BNB',                 'crypto', 'Exchange Token'),
('SOL',   'Solana',              'crypto', 'Layer 1'),
('XRP',   'XRP',                 'crypto', 'Payments'),
('ADA',   'Cardano',             'crypto', 'Layer 1'),
('AVAX',  'Avalanche',           'crypto', 'Layer 1'),
('DOT',   'Polkadot',            'crypto', 'Layer 0'),
('LINK',  'Chainlink',           'crypto', 'Oracle'),
('MATIC', 'Polygon',             'crypto', 'Layer 2'),
('LTC',   'Litecoin',            'crypto', 'Payments'),
('BCH',   'Bitcoin Cash',        'crypto', 'Payments'),
('ATOM',  'Cosmos',              'crypto', 'Interoperability'),
('UNI',   'Uniswap',             'crypto', 'DeFi'),
('AAVE',  'Aave',                'crypto', 'DeFi'),
('FIL',   'Filecoin',            'crypto', 'Storage'),
('ICP',   'Internet Computer',   'crypto', 'Layer 1'),
('ALGO',  'Algorand',            'crypto', 'Layer 1'),
('XLM',   'Stellar',             'crypto', 'Payments'),
('VET',   'VeChain',             'crypto', 'Supply Chain')

ON CONFLICT (ticker) DO NOTHING;
